[package]
name = "umbrella"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-parser = { git = "https://github.com/RyanSquared/ansi-parser-rs", version = "0.9.1" }
html-escape = "0.2.12"
